replicaCount: 3

image:
  repository: public.ecr.aws/n2z2i6h9/fast-api-test
  tag: v1.0
  pullPolicy: IfNotPresent


ingress:
  name: fastapi-test-2-ingress
  host: fastapi.sec.svc.local


serviceAccount:
  name: myapp-sa

vault:
  role: my-app-role
  secretPath: secret/data/fastapi

nodeSelector: {}
tolerations: []
affinity: {}
