apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fastapi-app.fullname" . }}
  labels:
    app: {{ include "fastapi-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "fastapi-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "fastapi-app.name" . }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"

        vault.hashicorp.com/role: "{{ .Values.vault.role }}"

        vault.hashicorp.com/agent-inject-secret-config: "{{ .Values.vault.secretPath }}"

        vault.hashicorp.com/agent-inject-template-config: |
          {{`{{- with secret "`}}{{ .Values.vault.secretPath }}{{`" -}}`}}
          {{`{{- range $k, $v := .Data.data }}`}}
          {{`{{ $k }}`}}={{`{{ $v }}`}}
          {{`{{- end }}`}}
          {{`{{- end }}`}}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: fastapi-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/sh" ]
          args:
            - "-c"
            - |
              # Check if secrets file exists
              if [ -f /vault/secrets/config ]; then
                # export all key=value pairs as environment variables
                export $(grep -v '^#' /vault/secrets/config | xargs)
              fi
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi