apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapi-app.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "fastapi-app.name" . }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
