apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flink-ingress
spec:
  rules:
    - host: flink.svc.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flink-jobmanager
                port:
                  number: 8081
